# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Shyam Rallapalli
tagline:          A blog about me
url:              http://shyamrallapalli.github.io
paginate:         1
baseurl:          /
author:
  name:           Shyam Rallapalli
  url:            https://twitter.com/shyamrallapalli
  email:          shyam.rallapalli@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/shyamrallapalli/shyamrallapalli.github.io
